artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1exDvwtVb3ZA5hotrWSQuu4iIAs_oD3s5/view?usp=sharing
  raw_data_file: artifacts/data_ingestion/data.csv
  train_data_file: artifacts/data_ingestion/train.csv
  test_data_file: artifacts/data_ingestion/test.csv
  

data_transformation:
  root_dir: artifacts/data_transformation
  train_data_file: artifacts/data_ingestion/train.csv
  test_data_file: artifacts/data_ingestion/test.csv
  
